name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
    - name: pack nuget packages
      run: dotnet pack --output nupkgs --no-restore --no-build
    - name: upload nuget package
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json