name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0' # любая поддерживаемая версия SDK. Важно, чтобы она была >= вашей целевой версии

    - name: Install dependencies
      run: dotnet restore

    - name: Install dotnet-proj-info
      run: dotnet tool install --global dotnet-proj-info

    - name: Extract NuGet Package Version
      id: extract_version
      run: |
        VERSION=$(dotnet-proj-info Ereoz.Abstractions/Ereoz.Abstractions.csproj --property Version)
        echo "::set-output name=version::$VERSION"

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release -o .

    - name: Push to GitHub Packages
      run: dotnet nuget push *.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate